exports.after = [
  { bank: "Sacombank", value: 7.3, threshold: "Dưới 200 triệu", period: 18 },
  { bank: "Sacombank", value: 7.5, threshold: "Dưới 200 triệu", period: 24 },
  { bank: "Sacombank", value: 7.6, threshold: "Dưới 200 triệu", period: 36 },
  { bank: "Sacombank", value: -10, threshold: "", period: 0 },
  { bank: "Sacombank", value: 4.5, threshold: "", period: 1 },
  { bank: "Sacombank", value: 4.6, threshold: "", period: 2 },
  { bank: "Sacombank", value: 6.2, threshold: "Dưới 200 triệu", period: 6 },
  { bank: "Eximbank", value: 0.2, threshold: "", period: 0 },
  { bank: "Eximbank", value: 4.7, threshold: "", period: 1 },
  { bank: "Eximbank", value: 4.7, threshold: "", period: 2 },
  { bank: "Eximbank", value: 7.2, threshold: "", period: 12 },
  { bank: "Eximbank", value: 7.4, threshold: "", period: 18 },
  { bank: "Eximbank", value: 7.5, threshold: "", period: 36 },
];
