exports.fools = [
  { bank: "Agribank", value: 0.2, threshold: "", period: 0 },
  { bank: "Agribank", value: 4.3, threshold: "", period: 1 },
  { bank: "Agribank", value: 4.3, threshold: "", period: 2 },
  { bank: "Agribank", value: 4.7, threshold: "", period: 3 },
  { bank: "Agribank", value: 5.1, threshold: "", period: 6 },
  { bank: "Agribank", value: 5.2, threshold: "", period: 9 },
  { bank: "Agribank", value: 6.8, threshold: "", period: 12 },
  { bank: "Agribank", value: 6.8, threshold: "", period: 13 },
  { bank: "Agribank", value: 6.8, threshold: "", period: 18 },
  { bank: "Agribank", value: 6.8, threshold: "", period: 24 },
  { bank: "BIDV", value: 0.1, threshold: "", period: 0 },
  { bank: "BIDV", value: 0.3, threshold: "", period: 1 },
  { bank: "BIDV", value: 4.3, threshold: "", period: 2 },
  { bank: "BIDV", value: 4.75, threshold: "", period: 3 },
  { bank: "BIDV", value: 5.1, threshold: "", period: 6 },
  { bank: "BIDV", value: 5.1, threshold: "", period: 9 },
  { bank: "BIDV", value: 6.8, threshold: "", period: 12 },
  { bank: "BIDV", value: 6.6, threshold: "", period: 13 },
  { bank: "BIDV", value: 6.6, threshold: "", period: 18 },
  { bank: "BIDV", value: 6.6, threshold: "", period: 24 },
  { bank: "BIDV", value: 6.6, threshold: "", period: 36 },
  { bank: "CB", value: 0.5, threshold: "", period: 0 },
  { bank: "CB", value: 4.75, threshold: "", period: 1 },
  { bank: "CB", value: 4.75, threshold: "", period: 2 },
  { bank: "CB", value: 4.75, threshold: "", period: 3 },
  { bank: "CB", value: 7.85, threshold: "", period: 6 },
  { bank: "CB", value: 7.85, threshold: "", period: 9 },
  { bank: "CB", value: 7.9, threshold: "", period: 12 },
  { bank: "CB", value: 7.95, threshold: "", period: 13 },
  { bank: "CB", value: 8.0, threshold: "", period: 18 },
  { bank: "CB", value: 8.0, threshold: "", period: 24 },
  { bank: "CB", value: 8.0, threshold: "", period: 36 },
  { bank: "GPBank", value: 0.5, threshold: "", period: 0 },
  { bank: "GPBank", value: 4.75, threshold: "", period: 1 },
  { bank: "GPBank", value: 4.75, threshold: "", period: 2 },
  { bank: "GPBank", value: 4.75, threshold: "", period: 3 },
  { bank: "GPBank", value: 7.25, threshold: "Từ 3 tỉ", period: 6 },
  { bank: "GPBank", value: 7.35, threshold: "Từ 3 tỉ", period: 9 },
  { bank: "GPBank", value: 7.45, threshold: "Từ 3 tỉ", period: 12 },
  { bank: "GPBank", value: 7.55, threshold: "Từ 3 tỉ", period: 13 },
  { bank: "GPBank", value: 7.2, threshold: "", period: 18 },
  { bank: "GPBank", value: 7.2, threshold: "", period: 24 },
  { bank: "GPBank", value: 7.2, threshold: "", period: 36 },
  { bank: "Oceanbank", value: 0.5, threshold: "", period: 0 },
  { bank: "Oceanbank", value: 4.75, threshold: "", period: 1 },
  { bank: "Oceanbank", value: 4.75, threshold: "", period: 2 },
  { bank: "Oceanbank", value: 4.75, threshold: "", period: 3 },
  { bank: "Oceanbank", value: 6.8, threshold: "", period: 6 },
  { bank: "Oceanbank", value: 6.4, threshold: "", period: 9 },
  { bank: "Oceanbank", value: 7.8, threshold: "", period: 12 },
  { bank: "Oceanbank", value: 7.5, threshold: "", period: 13 },
  { bank: "Oceanbank", value: 7.2, threshold: "", period: 18 },
  { bank: "Oceanbank", value: 7.3, threshold: "", period: 24 },
  { bank: "Oceanbank", value: 7.4, threshold: "", period: 36 },
  { bank: "Vietcombank", value: 0.1, threshold: "", period: 0 },
  { bank: "Vietcombank", value: 4.3, threshold: "", period: 1 },
  { bank: "Vietcombank", value: 4.3, threshold: "", period: 2 },
  { bank: "Vietcombank", value: 4.7, threshold: "", period: 3 },
  { bank: "Vietcombank", value: 5.1, threshold: "", period: 6 },
  { bank: "Vietcombank", value: 5.1, threshold: "", period: 9 },
  { bank: "Vietcombank", value: 6.6, threshold: "", period: 12 },
  { bank: "Vietcombank", value: -10, threshold: "", period: 13 },
  { bank: "Vietcombank", value: -10, threshold: "", period: 18 },
  { bank: "Vietcombank", value: 6.8, threshold: "", period: 24 },
  { bank: "Vietcombank", value: 6.5, threshold: "", period: 36 },
  { bank: "VietinBank", value: 0.1, threshold: "", period: 0 },
  { bank: "VietinBank", value: 4.3, threshold: "", period: 1 },
  { bank: "VietinBank", value: 4.3, threshold: "", period: 2 },
  { bank: "VietinBank", value: 4.7, threshold: "", period: 3 },
  { bank: "VietinBank", value: 5.1, threshold: "", period: 6 },
  { bank: "VietinBank", value: 5.1, threshold: "", period: 9 },
  { bank: "VietinBank", value: 6.8, threshold: "", period: 12 },
  { bank: "VietinBank", value: 6.6, threshold: "", period: 13 },
  { bank: "VietinBank", value: 6.7, threshold: "", period: 18 },
  { bank: "VietinBank", value: 6.8, threshold: "", period: 24 },
  { bank: "VietinBank", value: 6.6, threshold: "", period: 36 },
  { bank: "ACB", value: 4.75, threshold: "Từ 10 tỉ", period: 1 },
  { bank: "ACB", value: 4.75, threshold: "Từ 10 tỉ", period: 2 },
  { bank: "ACB", value: 4.75, threshold: "Từ 10 tỉ", period: 3 },
  { bank: "ACB", value: 6.6, threshold: "Từ 10 tỉ", period: 6 },
  { bank: "ACB", value: 6.9, threshold: "Từ 10 tỉ", period: 9 },
  { bank: "ACB", value: 7.0, threshold: "Từ 10 tỉ", period: 12 },
  { bank: "ACB", value: 7.1, threshold: "Từ 10 tỉ", period: 13 },
  { bank: "ACB", value: 7.45, threshold: "Từ 10 tỉ", period: 18 },
  { bank: "ACB", value: 7.45, threshold: "Từ 10 tỉ", period: 24 },
  { bank: "ACB", value: 7.8, threshold: "Từ 10 tỉ", period: 36 },
  { bank: "ABBANK", value: 0.4, threshold: "", period: 0 },
  { bank: "ABBANK", value: 4.75, threshold: "", period: 1 },
  { bank: "ABBANK", value: 4.75, threshold: "", period: 2 },
  { bank: "ABBANK", value: 4.75, threshold: "", period: 3 },
  { bank: "ABBANK", value: 6.8, threshold: "", period: 6 },
  { bank: "ABBANK", value: 7.0, threshold: "", period: 9 },
  { bank: "ABBANK", value: 7.6, threshold: "", period: 12 },
  { bank: "ABBANK", value: 8.3, threshold: "Từ 500 tỉ", period: 13 },
  { bank: "ABBANK", value: 7.7, threshold: "", period: 18 },
  { bank: "ABBANK", value: 7.7, threshold: "", period: 24 },
  { bank: "ABBANK", value: 7.7, threshold: "", period: 36 },
  { bank: "BacABank", value: 0.5, threshold: "", period: 0 },
  { bank: "BacABank", value: 4.75, threshold: "", period: 1 },
  { bank: "BacABank", value: 4.75, threshold: "", period: 2 },
  { bank: "BacABank", value: 4.75, threshold: "", period: 3 },
  { bank: "BacABank", value: 7.5, threshold: "", period: 6 },
  { bank: "BacABank", value: 7.6, threshold: "", period: 9 },
  { bank: "BacABank", value: 7.8, threshold: "", period: 12 },
  { bank: "BacABank", value: 7.8, threshold: "", period: 13 },
  { bank: "BacABank", value: 7.8, threshold: "", period: 18 },
  { bank: "BacABank", value: 7.8, threshold: "", period: 24 },
  { bank: "BacABank", value: 7.8, threshold: "", period: 36 },
  { bank: "BaoVietBank", value: 0.5, threshold: "", period: 0 },
  { bank: "BaoVietBank", value: 4.75, threshold: "", period: 1 },
  { bank: "BaoVietBank", value: 4.75, threshold: "", period: 2 },
  { bank: "BaoVietBank", value: 4.75, threshold: "", period: 3 },
  { bank: "BaoVietBank", value: 6.85, threshold: "", period: 6 },
  { bank: "BaoVietBank", value: 6.9, threshold: "", period: 9 },
  { bank: "BaoVietBank", value: 7.95, threshold: "", period: 12 },
  { bank: "BaoVietBank", value: 7.99, threshold: "", period: 13 },
  { bank: "BaoVietBank", value: 7.6, threshold: "", period: 18 },
  { bank: "BaoVietBank", value: 7.6, threshold: "", period: 24 },
  { bank: "BaoVietBank", value: 7.6, threshold: "", period: 36 },
  { bank: "BIDV", value: 0.1, threshold: "", period: 0 },
  { bank: "BIDV", value: 4.3, threshold: "", period: 1 },
  { bank: "BIDV", value: 4.3, threshold: "", period: 2 },
  { bank: "BIDV", value: 4.75, threshold: "", period: 3 },
  { bank: "BIDV", value: 5.3, threshold: "", period: 6 },
  { bank: "BIDV", value: 5.3, threshold: "", period: 9 },
  { bank: "BIDV", value: 6.8, threshold: "", period: 12 },
  { bank: "BIDV", value: 6.8, threshold: "", period: 13 },
  { bank: "BIDV", value: 6.8, threshold: "", period: 18 },
  { bank: "BIDV", value: 6.8, threshold: "", period: 24 },
  { bank: "BIDV", value: 6.8, threshold: "", period: 36 },
  { bank: "DongABank", value: 4.75, threshold: "", period: 1 },
  { bank: "DongABank", value: 4.75, threshold: "", period: 2 },
  { bank: "DongABank", value: 4.75, threshold: "", period: 3 },
  { bank: "DongABank", value: 7.0, threshold: "", period: 6 },
  { bank: "DongABank", value: 7.2, threshold: "", period: 9 },
  { bank: "DongABank", value: 7.4, threshold: "", period: 12 },
  { bank: "DongABank", value: 7.6, threshold: "", period: 13 },
  { bank: "DongABank", value: 7.6, threshold: "", period: 18 },
  { bank: "DongABank", value: 7.6, threshold: "", period: 24 },
  { bank: "DongABank", value: 7.6, threshold: "", period: 36 },
  { bank: "Eximbank", value: 0.3, threshold: "", period: 0 },
  { bank: "Eximbank", value: 4.6, threshold: "", period: 1 },
  { bank: "Eximbank", value: 4.75, threshold: "", period: 2 },
  { bank: "Eximbank", value: 4.75, threshold: "", period: 3 },
  { bank: "Eximbank", value: 5.6, threshold: "", period: 6 },
  { bank: "Eximbank", value: 5.8, threshold: "", period: 9 },
  { bank: "Eximbank", value: 7.4, threshold: "", period: 12 },
  { bank: "Eximbank", value: 8.4, threshold: "", period: 13 },
  { bank: "Eximbank", value: 8.0, threshold: "", period: 18 },
  { bank: "Eximbank", value: 8.4, threshold: "", period: 24 },
  { bank: "Eximbank", value: 8.0, threshold: "", period: 36 },
  { bank: "HDBank", value: 4.75, threshold: "", period: 1 },
  { bank: "HDBank", value: 4.75, threshold: "", period: 2 },
  { bank: "HDBank", value: 4.75, threshold: "", period: 3 },
  { bank: "HDBank", value: 6.8, threshold: "", period: 6 },
  { bank: "HDBank", value: 6.8, threshold: "", period: 9 },
  { bank: "HDBank", value: 7.3, threshold: "", period: 12 },
  { bank: "HDBank", value: 7.4, threshold: "", period: 13 },
  { bank: "HDBank", value: 7.4, threshold: "", period: 18 },
  { bank: "HDBank", value: 7.0, threshold: "", period: 24 },
  { bank: "HDBank", value: 7.0, threshold: "", period: 36 },
  { bank: "KienLongBank", value: 4.75, threshold: "", period: 1 },
  { bank: "KienLongBank", value: 4.75, threshold: "", period: 2 },
  { bank: "KienLongBank", value: 4.75, threshold: "", period: 3 },
  { bank: "KienLongBank", value: 7.0, threshold: "", period: 6 },
  { bank: "KienLongBank", value: 7.0, threshold: "", period: 9 },
  { bank: "KienLongBank", value: 7.6, threshold: "", period: 12 },
  { bank: "KienLongBank", value: 7.8, threshold: "", period: 13 },
  { bank: "KienLongBank", value: 8.0, threshold: "", period: 18 },
  { bank: "KienLongBank", value: 8.0, threshold: "", period: 24 },
  { bank: "KienLongBank", value: 7.8, threshold: "", period: 36 },
  { bank: "LienVietPostBank", value: 4.3, threshold: "", period: 1 },
  { bank: "LienVietPostBank", value: 4.3, threshold: "", period: 2 },
  { bank: "LienVietPostBank", value: 4.75, threshold: "", period: 3 },
  { bank: "LienVietPostBank", value: 5.3, threshold: "", period: 6 },
  { bank: "LienVietPostBank", value: 5.4, threshold: "", period: 9 },
  { bank: "LienVietPostBank", value: 6.8, threshold: "", period: 12 },
  { bank: "LienVietPostBank", value: 6.8, threshold: "", period: 13 },
  { bank: "LienVietPostBank", value: 6.9, threshold: "", period: 18 },
  { bank: "LienVietPostBank", value: 6.9, threshold: "", period: 24 },
  { bank: "LienVietPostBank", value: 6.9, threshold: "", period: 36 },
  { bank: "MBB", value: 0.3, threshold: "", period: 0 },
  { bank: "MBB", value: 4.75, threshold: "", period: 1 },
  { bank: "MBB", value: 4.75, threshold: "", period: 2 },
  { bank: "MBB", value: 4.75, threshold: "", period: 3 },
  { bank: "MBB", value: 6.4, threshold: "", period: 6 },
  { bank: "MBB", value: 6.4, threshold: "", period: 9 },
  { bank: "MBB", value: 7.4, threshold: "Từ 200 tỉ", period: 12 },
  { bank: "MBB", value: 6.7, threshold: "", period: 13 },
  { bank: "MBB", value: 7.3, threshold: "", period: 18 },
  { bank: "MBB", value: 7.6, threshold: "Từ 200 tỉ", period: 24 },
  { bank: "MBB", value: 7.4, threshold: "", period: 36 },
  { bank: "MSB", value: 4.75, threshold: "Từ  1 tỉ", period: 1 },
  { bank: "MSB", value: 4.75, threshold: "Từ  1 tỉ", period: 2 },
  { bank: "MSB", value: 4.75, threshold: "Từ  1 tỉ", period: 3 },
  { bank: "MSB", value: 6.8, threshold: "Từ  1 tỉ", period: 6 },
  { bank: "MSB", value: 6.9, threshold: "Từ  1 tỉ", period: 9 },
  { bank: "MSB", value: 7.1, threshold: "Từ  1 tỉ", period: 12 },
  { bank: "MSB", value: 7.2, threshold: "Từ  1 tỉ", period: 13 },
  { bank: "MSB", value: 7.5, threshold: "Từ  1 tỉ", period: 18 },
  { bank: "MSB", value: 7.6, threshold: "Từ  1 tỉ", period: 24 },
  { bank: "MSB", value: 7.6, threshold: "Từ  1 tỉ", period: 36 },
  { bank: "Nam A Bank", value: 0.5, threshold: "", period: 0 },
  { bank: "Nam A Bank", value: 4.75, threshold: "", period: 1 },
  { bank: "Nam A Bank", value: 4.75, threshold: "", period: 2 },
  { bank: "Nam A Bank", value: 4.75, threshold: "", period: 3 },
  { bank: "Nam A Bank", value: 6.8, threshold: "", period: 6 },
  { bank: "Nam A Bank", value: 6.9, threshold: "", period: 9 },
  { bank: "Nam A Bank", value: 7.8, threshold: "", period: 12 },
  { bank: "Nam A Bank", value: 7.5, threshold: "", period: 18 },
  { bank: "Nam A Bank", value: 7.5, threshold: "", period: 36 },
  { bank: "NCB", value: 0.3, threshold: "", period: 0 },
  { bank: "NCB", value: 4.5, threshold: "", period: 1 },
  { bank: "NCB", value: 4.6, threshold: "", period: 2 },
  { bank: "NCB", value: 4.75, threshold: "", period: 3 },
  { bank: "NCB", value: 7.5, threshold: "", period: 6 },
  { bank: "NCB", value: 7.55, threshold: "", period: 9 },
  { bank: "NCB", value: 8.0, threshold: "", period: 12 },
  { bank: "NCB", value: 8.1, threshold: "", period: 13 },
  { bank: "NCB", value: 8.15, threshold: "", period: 18 },
  { bank: "NCB", value: 8.3, threshold: "", period: 24 },
  { bank: "NCB", value: 8.3, threshold: "", period: 36 },
  { bank: "OCB", value: 0.1, threshold: "", period: 0 },
  { bank: "OCB", value: 4.6, threshold: "", period: 1 },
  { bank: "OCB", value: 4.7, threshold: "", period: 2 },
  { bank: "OCB", value: 4.75, threshold: "", period: 3 },
  { bank: "OCB", value: 7.0, threshold: "", period: 6 },
  { bank: "OCB", value: 7.1, threshold: "", period: 9 },
  { bank: "OCB", value: 7.2, threshold: "", period: 12 },
  { bank: "OCB", value: 7.3, threshold: "", period: 18 },
  { bank: "OCB", value: 7.5, threshold: "", period: 24 },
  { bank: "OCB", value: 7.5, threshold: "", period: 36 },
  { bank: "PGBank", value: 4.75, threshold: "", period: 1 },
  { bank: "PGBank", value: 4.75, threshold: "", period: 2 },
  { bank: "PGBank", value: 4.75, threshold: "", period: 3 },
  { bank: "PGBank", value: 7.3, threshold: "", period: 6 },
  { bank: "PGBank", value: 7.3, threshold: "", period: 9 },
  { bank: "PGBank", value: 7.8, threshold: "", period: 12 },
  { bank: "PGBank", value: 8.0, threshold: "", period: 13 },
  { bank: "PGBank", value: 8.0, threshold: "", period: 18 },
  { bank: "PGBank", value: 8.0, threshold: "", period: 24 },
  { bank: "PGBank", value: 8.0, threshold: "", period: 36 },
  { bank: "PVcomBank", value: 0, threshold: "", period: 0 },
  { bank: "PVcomBank", value: 4.75, threshold: "", period: 1 },
  { bank: "PVcomBank", value: 4.75, threshold: "", period: 2 },
  { bank: "PVcomBank", value: 0, threshold: "", period: 3 },
  { bank: "PVcomBank", value: 7.1, threshold: "", period: 6 },
  { bank: "PVcomBank", value: 7.4, threshold: "", period: 9 },
  { bank: "PVcomBank", value: 7.99, threshold: "", period: 12 },
  { bank: "PVcomBank", value: 7.99, threshold: "", period: 13 },
  { bank: "PVcomBank", value: 7.99, threshold: "", period: 18 },
  { bank: "PVcomBank", value: 7.99, threshold: "", period: 24 },
  { bank: "PVcomBank", value: 7.99, threshold: "", period: 36 },
  { bank: "Sacombank", value: 4.3, threshold: "", period: 1 },
  { bank: "Sacombank", value: 4.3, threshold: "", period: 2 },
  { bank: "Sacombank", value: 4.7, threshold: "", period: 3 },
  { bank: "Sacombank", value: 6.1, threshold: "Dưới 200 triệu", period: 6 },
  { bank: "Sacombank", value: 6.4, threshold: "", period: 9 },
  { bank: "Sacombank", value: 6.8, threshold: "Dưới 200 triệu", period: 12 },
  { bank: "Sacombank", value: 7.9, threshold: "", period: 13 },
  { bank: "Sacombank", value: 7.5, threshold: "Dưới 200 triệu", period: 18 },
  { bank: "Sacombank", value: 7.7, threshold: "Dưới 200 triệu", period: 24 },
  { bank: "Sacombank", value: 7.8, threshold: "Dưới 200 triệu", period: 36 },
  { bank: "Saigonbank", value: 0.2, threshold: "", period: 0 },
  { bank: "Saigonbank", value: 4.75, threshold: "", period: 1 },
  { bank: "Saigonbank", value: 4.75, threshold: "", period: 2 },
  { bank: "Saigonbank", value: 4.75, threshold: "", period: 3 },
  { bank: "Saigonbank", value: 6.6, threshold: "", period: 6 },
  { bank: "Saigonbank", value: 6.6, threshold: "", period: 9 },
  { bank: "Saigonbank", value: 7.2, threshold: "", period: 12 },
  { bank: "Saigonbank", value: 7.6, threshold: "", period: 13 },
  { bank: "Saigonbank", value: 7.6, threshold: "", period: 18 },
  { bank: "Saigonbank", value: 7.6, threshold: "", period: 24 },
  { bank: "Saigonbank", value: 7.6, threshold: "", period: 36 },
  { bank: "SCB", value: 4.75, threshold: "", period: 1 },
  { bank: "SCB", value: 4.75, threshold: "", period: 2 },
  { bank: "SCB", value: 4.75, threshold: "", period: 3 },
  { bank: "SCB", value: 7.1, threshold: "", period: 6 },
  { bank: "SCB", value: 7.1, threshold: "", period: 9 },
  { bank: "SCB", value: 7.5, threshold: "", period: 12 },
  { bank: "SCB", value: 7.7, threshold: "", period: 13 },
  { bank: "SCB", value: 7.7, threshold: "", period: 18 },
  { bank: "SCB", value: 7.55, threshold: "", period: 24 },
  { bank: "SCB", value: 7.55, threshold: "", period: 36 },
  { bank: "SeABank", value: 4.75, threshold: "", period: 1 },
  { bank: "SeABank", value: 4.75, threshold: "", period: 2 },
  { bank: "SeABank", value: 4.75, threshold: "", period: 3 },
  { bank: "SeABank", value: 5.8, threshold: "", period: 6 },
  { bank: "SeABank", value: 6.2, threshold: "", period: 9 },
  { bank: "SeABank", value: 6.8, threshold: "", period: 12 },
  { bank: "SeABank", value: 6.85, threshold: "", period: 18 },
  { bank: "SeABank", value: 6.9, threshold: "", period: 24 },
  { bank: "SeABank", value: 6.95, threshold: "", period: 36 },
  { bank: "SHB", value: 0.2, threshold: "Từ 2 tỉ", period: 0 },
  { bank: "SHB", value: 4.6, threshold: "Từ 2 tỉ", period: 1 },
  { bank: "SHB", value: 4.7, threshold: "Từ 2 tỉ", period: 2 },
  { bank: "SHB", value: 4.75, threshold: "Từ 2 tỉ", period: 3 },
  { bank: "SHB", value: 6.9, threshold: "Từ 2 tỉ", period: 6 },
  { bank: "SHB", value: 7.0, threshold: "Từ 2 tỉ", period: 9 },
  { bank: "SHB", value: 7.1, threshold: "Từ 2 tỉ", period: 12 },
  { bank: "SHB", value: 7.2, threshold: "Từ 2 tỉ", period: 13 },
  { bank: "SHB", value: 7.4, threshold: "Từ 2 tỉ", period: 18 },
  { bank: "SHB", value: 7.4, threshold: "Từ 2 tỉ", period: 24 },
  { bank: "SHB", value: 7.5, threshold: "Từ 2 tỉ", period: 36 },
  { bank: "Techcombank", value: 0.1, threshold: "", period: 0 },
  {
    bank: "Techcombank",
    value: 4.5,
    threshold: "Từ 3 tỉ và KH trên 50 tuổi",
    period: 1
  },
  {
    bank: "Techcombank",
    value: 4.5,
    threshold: "Từ 3 tỉ và KH trên 50 tuổi",
    period: 2
  },
  {
    bank: "Techcombank",
    value: 4.5,
    threshold: "Từ 3 tỉ và KH trên 50 tuổi",
    period: 3
  },
  {
    bank: "Techcombank",
    value: 6.1,
    threshold: "Từ 3 tỉ và KH trên 50 tuổi",
    period: 6
  },
  {
    bank: "Techcombank",
    value: 5.6,
    threshold: "Từ 3 tỉ và KH trên 50 tuổi",
    period: 9
  },
  {
    bank: "Techcombank",
    value: 6.2,
    threshold: "Từ 3 tỉ và KH trên 50 tuổi",
    period: 12
  },
  {
    bank: "Techcombank",
    value: 6.0,
    threshold: "Từ 3 tỉ và KH trên 50 tuổi",
    period: 13
  },
  {
    bank: "Techcombank",
    value: 6.2,
    threshold: "Từ 3 tỉ và KH trên 50 tuổi",
    period: 18
  },
  {
    bank: "Techcombank",
    value: 6.1,
    threshold: "Từ 3 tỉ và KH trên 50 tuổi",
    period: 24
  },
  {
    bank: "Techcombank",
    value: 6.1,
    threshold: "Từ 3 tỉ và KH trên 50 tuổi",
    period: 36
  },
  { bank: "TPBank", value: 0.5, threshold: "", period: 0 },
  { bank: "TPBank", value: 4.75, threshold: "", period: 1 },
  { bank: "TPBank", value: 4.75, threshold: "", period: 2 },
  { bank: "TPBank", value: 4.75, threshold: "", period: 3 },
  { bank: "TPBank", value: 6.4, threshold: "", period: 6 },
  { bank: "TPBank", value: 6.9, threshold: "", period: 9 },
  { bank: "TPBank", value: 7.4, threshold: "", period: 12 },
  { bank: "TPBank", value: 7.55, threshold: "", period: 13 },
  { bank: "TPBank", value: 7.6, threshold: "", period: 18 },
  { bank: "TPBank", value: 7.6, threshold: "", period: 24 },
  { bank: "TPBank", value: 7.6, threshold: "", period: 36 },
  { bank: "VIB", value: 0.5, threshold: "", period: 0 },
  { bank: "VIB", value: 4.75, threshold: "Từ 5 tỉ", period: 1 },
  { bank: "VIB", value: 4.75, threshold: "Từ 5 tỉ", period: 2 },
  { bank: "VIB", value: 4.75, threshold: "Từ 5 tỉ", period: 3 },
  { bank: "VIB", value: 6.9, threshold: "Từ 5 tỉ", period: 6 },
  { bank: "VIB", value: 6.9, threshold: "Từ 5 tỉ", period: 9 },
  { bank: "VIB", value: 7.59, threshold: "Từ 5 tỉ", period: 12 },
  { bank: "VIB", value: 7.59, threshold: "Từ 5 tỉ", period: 13 },
  { bank: "VIB", value: 7.5, threshold: "Từ 5 tỉ", period: 18 },
  { bank: "VIB", value: 7.5, threshold: "Từ 5 tỉ", period: 24 },
  { bank: "VIB", value: 7.5, threshold: "Từ 5 tỉ", period: 36 },
  { bank: "VietABank", value: 4.65, threshold: "", period: 1 },
  { bank: "VietABank", value: 4.65, threshold: "", period: 2 },
  { bank: "VietABank", value: 4.65, threshold: "", period: 3 },
  { bank: "VietABank", value: 7.0, threshold: "", period: 6 },
  { bank: "VietABank", value: 7.1, threshold: "", period: 9 },
  { bank: "VietABank", value: 7.6, threshold: "", period: 12 },
  { bank: "VietABank", value: 7.7, threshold: "", period: 13 },
  { bank: "VietABank", value: 7.7, threshold: "", period: 18 },
  { bank: "VietABank", value: 7.9, threshold: "", period: 24 },
  { bank: "VietABank", value: 7.7, threshold: "", period: 36 },
  { bank: "VietBank", value: 4.75, threshold: "", period: 1 },
  { bank: "VietBank", value: 4.75, threshold: "", period: 2 },
  { bank: "VietBank", value: 4.75, threshold: "", period: 3 },
  { bank: "VietBank", value: 7.5, threshold: "", period: 6 },
  { bank: "VietBank", value: 7.8, threshold: "", period: 9 },
  { bank: "VietBank", value: 7.9, threshold: "", period: 12 },
  { bank: "VietBank", value: 8.0, threshold: "", period: 13 },
  { bank: "VietBank", value: 8.1, threshold: "", period: 18 },
  { bank: "VietBank", value: 8.2, threshold: "", period: 24 },
  { bank: "VietBank", value: 8.2, threshold: "", period: 36 },
  { bank: "VietCapitalBank", value: 4.65, threshold: "", period: 1 },
  { bank: "VietCapitalBank", value: 4.65, threshold: "", period: 2 },
  { bank: "VietCapitalBank", value: 4.7, threshold: "", period: 3 },
  { bank: "VietCapitalBank", value: 7.3, threshold: "", period: 6 },
  { bank: "VietCapitalBank", value: 7.5, threshold: "", period: 9 },
  { bank: "VietCapitalBank", value: 7.8, threshold: "", period: 12 },
  { bank: "VietCapitalBank", value: 8.2, threshold: "", period: 13 },
  { bank: "VietCapitalBank", value: 8.0, threshold: "", period: 18 },
  { bank: "VietCapitalBank", value: 8.1, threshold: "", period: 24 },
  { bank: "VietCapitalBank", value: 8.1, threshold: "", period: 36 },
  { bank: "VPBank", value: 4.55, threshold: "Từ 10 tỉ", period: 1 },
  { bank: "VPBank", value: 4.55, threshold: "Từ 10 tỉ", period: 2 },
  { bank: "VPBank", value: 4.65, threshold: "Từ 10 tỉ", period: 3 },
  { bank: "VPBank", value: 6.9, threshold: "Từ 10 tỉ", period: 6 },
  { bank: "VPBank", value: 6.9, threshold: "Từ 10 tỉ", period: 9 },
  { bank: "VPBank", value: 7.0, threshold: "Từ 10 tỉ", period: 12 },
  { bank: "VPBank", value: 7.0, threshold: "Từ 10 tỉ", period: 13 },
  { bank: "VPBank", value: 7.1, threshold: "Từ 10 tỉ", period: 18 },
  { bank: "VPBank", value: 7.1, threshold: "Từ 10 tỉ", period: 24 },
  { bank: "VPBank", value: 7.1, threshold: "Từ 10 tỉ", period: 36 },
  { bank: "ANZ Bank", value: 0.0, threshold: "", period: 0 },
  { bank: "ANZ Bank", value: 1.5, threshold: "", period: 1 },
  { bank: "ANZ Bank", value: 1.5, threshold: "", period: 2 },
  { bank: "ANZ Bank", value: 1.5, threshold: "", period: 3 },
  { bank: "ANZ Bank", value: 1.5, threshold: "", period: 6 },
  { bank: "ANZ Bank", value: -100, threshold: "", period: 9 },
  { bank: "ANZ Bank", value: -100, threshold: "", period: 12 },
  { bank: "ANZ Bank", value: -100, threshold: "", period: 13 },
  { bank: "ANZ Bank", value: -100, threshold: "", period: 18 },
  { bank: "ANZ Bank", value: -100, threshold: "", period: 24 },
  { bank: "ANZ Bank", value: -100, threshold: "", period: 36 },
  { bank: "HSBC", value: 0.5, threshold: "", period: 1 },
  { bank: "HSBC", value: 0.5, threshold: "", period: 2 },
  { bank: "HSBC", value: 1.25, threshold: "", period: 3 },
  { bank: "HSBC", value: 1.75, threshold: "", period: 6 },
  { bank: "HSBC", value: 1.75, threshold: "", period: 9 },
  { bank: "HSBC", value: 2.75, threshold: "", period: 12 },
  { bank: "HSBC", value: 2.75, threshold: "", period: 18 },
  { bank: "HSBC", value: 2.75, threshold: "", period: 24 },
  { bank: "HSBC", value: 2.75, threshold: "", period: 36 },
  { bank: "Standard Chartered", value: 1.32, threshold: "", period: 1 },
  { bank: "Standard Chartered", value: 1.58, threshold: "", period: 2 },
  { bank: "Standard Chartered", value: 1.87, threshold: "", period: 3 },
  { bank: "Standard Chartered", value: 1.87, threshold: "", period: 6 },
  { bank: "Standard Chartered", value: 1.87, threshold: "", period: 9 },
  { bank: "Standard Chartered", value: 1.87, threshold: "", period: 12 },
  { bank: "Standard Chartered", value: 1.87, threshold: "", period: 13 },
  { bank: "Standard Chartered", value: 1.87, threshold: "", period: 18 },
  { bank: "Standard Chartered", value: 1.87, threshold: "", period: 24 },
  { bank: "Standard Chartered", value: 1.87, threshold: "", period: 36 },
  { bank: "IVB", value: 0, threshold: "", period: 0 },
  { bank: "IVB", value: 4.75, threshold: "", period: 1 },
  { bank: "IVB", value: 4.75, threshold: "", period: 2 },
  { bank: "IVB", value: 4.75, threshold: "", period: 3 },
  { bank: "IVB", value: 6.8, threshold: "", period: 6 },
  { bank: "IVB", value: 6.9, threshold: "", period: 9 },
  { bank: "IVB", value: 7.6, threshold: "", period: 12 },
  { bank: "IVB", value: 7.7, threshold: "", period: 13 },
  { bank: "IVB", value: 7.8, threshold: "", period: 18 },
  { bank: "IVB", value: 7.9, threshold: "", period: 24 },
  { bank: "IVB", value: 7.9, threshold: "", period: 36 }
];
