exports.twilight = [
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'Agribank',
    value: 0.2,
    threshold: '',
    period: 0,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'Agribank',
    value: 4.3,
    threshold: '',
    period: 1,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'Agribank',
    value: 4.3,
    threshold: '',
    period: 2,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'Agribank',
    value: 4.7,
    threshold: '',
    period: 3,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'Agribank',
    value: 5.1,
    threshold: '',
    period: 6,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'Agribank',
    value: 5.2,
    threshold: '',
    period: 9,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'Agribank',
    value: 6.8,
    threshold: '',
    period: 12,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'Agribank',
    value: 6.8,
    threshold: '',
    period: 13,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'Agribank',
    value: 6.8,
    threshold: '',
    period: 18,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'Agribank',
    value: 6.8,
    threshold: '',
    period: 24,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'Agribank',
    value: -10,
    threshold: '',
    period: 36,
  },
  { lastUpdate: '2020-04-17', online: true, bank: 'BIDV', value: 0.1, threshold: '', period: 0 },
  { lastUpdate: '2020-04-17', online: true, bank: 'BIDV', value: 0.3, threshold: '', period: 1 },
  { lastUpdate: '2020-04-17', online: true, bank: 'BIDV', value: 4.3, threshold: '', period: 2 },
  { lastUpdate: '2020-04-17', online: true, bank: 'BIDV', value: 4.75, threshold: '', period: 3 },
  { lastUpdate: '2020-04-17', online: true, bank: 'BIDV', value: 5.1, threshold: '', period: 6 },
  { lastUpdate: '2020-04-17', online: true, bank: 'BIDV', value: 5.1, threshold: '', period: 9 },
  { lastUpdate: '2020-04-17', online: true, bank: 'BIDV', value: 6.8, threshold: '', period: 12 },
  { lastUpdate: '2020-04-17', online: true, bank: 'BIDV', value: 6.6, threshold: '', period: 13 },
  { lastUpdate: '2020-04-17', online: true, bank: 'BIDV', value: 6.6, threshold: '', period: 18 },
  { lastUpdate: '2020-04-17', online: true, bank: 'BIDV', value: 6.6, threshold: '', period: 24 },
  { lastUpdate: '2020-04-17', online: true, bank: 'BIDV', value: 6.6, threshold: '', period: 36 },
  { lastUpdate: '2020-04-17', online: true, bank: 'CB', value: 0.5, threshold: '', period: 0 },
  { lastUpdate: '2020-04-17', online: true, bank: 'CB', value: 4.75, threshold: '', period: 1 },
  { lastUpdate: '2020-04-17', online: true, bank: 'CB', value: 4.75, threshold: '', period: 2 },
  { lastUpdate: '2020-04-17', online: true, bank: 'CB', value: 4.75, threshold: '', period: 3 },
  { lastUpdate: '2020-04-17', online: true, bank: 'CB', value: 8.3, threshold: '', period: 6 },
  { lastUpdate: '2020-04-17', online: true, bank: 'CB', value: 8.2, threshold: '', period: 9 },
  { lastUpdate: '2020-04-17', online: true, bank: 'CB', value: 8.4, threshold: '', period: 12 },
  { lastUpdate: '2020-04-17', online: true, bank: 'CB', value: -10, threshold: '', period: 13 },
  { lastUpdate: '2020-04-17', online: true, bank: 'CB', value: -10, threshold: '', period: 18 },
  { lastUpdate: '2020-04-17', online: true, bank: 'CB', value: -10, threshold: '', period: 24 },
  { lastUpdate: '2020-04-17', online: true, bank: 'CB', value: -10, threshold: '', period: 36 },
  { lastUpdate: '2020-04-17', online: true, bank: 'GPBank', value: 0.5, threshold: '', period: 0 },
  { lastUpdate: '2020-04-17', online: true, bank: 'GPBank', value: 4.75, threshold: '', period: 1 },
  { lastUpdate: '2020-04-17', online: true, bank: 'GPBank', value: 4.75, threshold: '', period: 2 },
  { lastUpdate: '2020-04-17', online: true, bank: 'GPBank', value: 4.75, threshold: '', period: 3 },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'GPBank',
    value: 7.05,
    threshold: 'Từ 3 tỉ',
    period: 6,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'GPBank',
    value: 7.15,
    threshold: 'Từ 3 tỉ',
    period: 9,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'GPBank',
    value: 7.25,
    threshold: 'Từ 3 tỉ',
    period: 12,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'GPBank',
    value: 7.35,
    threshold: 'Từ 3 tỉ',
    period: 13,
  },
  { lastUpdate: '2020-04-17', online: true, bank: 'GPBank', value: 7.0, threshold: '', period: 18 },
  { lastUpdate: '2020-04-17', online: true, bank: 'GPBank', value: 7.0, threshold: '', period: 24 },
  { lastUpdate: '2020-04-17', online: true, bank: 'GPBank', value: 7.0, threshold: '', period: 36 },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'Oceanbank',
    value: 0.5,
    threshold: '',
    period: 0,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'Oceanbank',
    value: 4.75,
    threshold: '',
    period: 1,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'Oceanbank',
    value: 4.75,
    threshold: '',
    period: 2,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'Oceanbank',
    value: 4.75,
    threshold: '',
    period: 3,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'Oceanbank',
    value: 6.5,
    threshold: '',
    period: 6,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'Oceanbank',
    value: 6.1,
    threshold: '',
    period: 9,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'Oceanbank',
    value: 7.5,
    threshold: '',
    period: 12,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'Oceanbank',
    value: 7.2,
    threshold: '',
    period: 13,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'Oceanbank',
    value: 6.9,
    threshold: '',
    period: 18,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'Oceanbank',
    value: 7.0,
    threshold: '',
    period: 24,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'Oceanbank',
    value: 7.1,
    threshold: '',
    period: 36,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'Vietcombank',
    value: 0.1,
    threshold: '',
    period: 0,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'Vietcombank',
    value: 4.3,
    threshold: '',
    period: 1,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'Vietcombank',
    value: 4.3,
    threshold: '',
    period: 2,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'Vietcombank',
    value: 4.7,
    threshold: '',
    period: 3,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'Vietcombank',
    value: 5.1,
    threshold: '',
    period: 6,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'Vietcombank',
    value: 5.1,
    threshold: '',
    period: 9,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'Vietcombank',
    value: 6.6,
    threshold: '',
    period: 12,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'Vietcombank',
    value: -10,
    threshold: '',
    period: 13,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'Vietcombank',
    value: -10,
    threshold: '',
    period: 18,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'Vietcombank',
    value: 6.8,
    threshold: '',
    period: 24,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'Vietcombank',
    value: 6.5,
    threshold: '',
    period: 36,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'VietinBank',
    value: 0.1,
    threshold: '',
    period: 0,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'VietinBank',
    value: 4.3,
    threshold: '',
    period: 1,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'VietinBank',
    value: 4.3,
    threshold: '',
    period: 2,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'VietinBank',
    value: 4.7,
    threshold: '',
    period: 3,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'VietinBank',
    value: 5.1,
    threshold: '',
    period: 6,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'VietinBank',
    value: 5.1,
    threshold: '',
    period: 9,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'VietinBank',
    value: 6.8,
    threshold: '',
    period: 12,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'VietinBank',
    value: 6.6,
    threshold: '',
    period: 13,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'VietinBank',
    value: 6.7,
    threshold: '',
    period: 18,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'VietinBank',
    value: 6.8,
    threshold: '',
    period: 24,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'VietinBank',
    value: 6.6,
    threshold: '',
    period: 36,
  },
  { lastUpdate: '2020-04-17', online: true, bank: 'ACB', value: -10, threshold: '', period: 0 },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'ACB',
    value: 4.6,
    threshold: 'Từ 10 tỉ',
    period: 1,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'ACB',
    value: 4.65,
    threshold: 'Từ 10 tỉ',
    period: 2,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'ACB',
    value: 4.75,
    threshold: 'Từ 10 tỉ',
    period: 3,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'ACB',
    value: 6.8,
    threshold: 'Từ 10 tỉ',
    period: 6,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'ACB',
    value: 6.9,
    threshold: 'Từ 10 tỉ',
    period: 9,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'ACB',
    value: 7.0,
    threshold: 'Từ 10 tỉ',
    period: 12,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'ACB',
    value: 7.1,
    threshold: 'Từ 10 tỉ',
    period: 13,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'ACB',
    value: 7.35,
    threshold: 'Từ 10 tỉ',
    period: 18,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'ACB',
    value: 7.35,
    threshold: 'Từ 10 tỉ',
    period: 24,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'ACB',
    value: 7.35,
    threshold: 'Từ 10 tỉ',
    period: 36,
  },
  { lastUpdate: '2020-04-17', online: true, bank: 'ABBANK', value: 0.4, threshold: '', period: 0 },
  { lastUpdate: '2020-04-17', online: true, bank: 'ABBANK', value: 4.75, threshold: '', period: 1 },
  { lastUpdate: '2020-04-17', online: true, bank: 'ABBANK', value: 4.75, threshold: '', period: 2 },
  { lastUpdate: '2020-04-17', online: true, bank: 'ABBANK', value: 4.75, threshold: '', period: 3 },
  { lastUpdate: '2020-04-17', online: true, bank: 'ABBANK', value: 6.8, threshold: '', period: 6 },
  { lastUpdate: '2020-04-17', online: true, bank: 'ABBANK', value: 7.0, threshold: '', period: 9 },
  { lastUpdate: '2020-04-17', online: true, bank: 'ABBANK', value: 7.6, threshold: '', period: 12 },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'ABBANK',
    value: 8.3,
    threshold: 'Từ 500 tỉ',
    period: 13,
  },
  { lastUpdate: '2020-04-17', online: true, bank: 'ABBANK', value: 7.8, threshold: '', period: 18 },
  { lastUpdate: '2020-04-17', online: true, bank: 'ABBANK', value: 7.8, threshold: '', period: 24 },
  { lastUpdate: '2020-04-17', online: true, bank: 'ABBANK', value: 7.8, threshold: '', period: 36 },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'BacABank',
    value: 0.5,
    threshold: '',
    period: 0,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'BacABank',
    value: 4.75,
    threshold: '',
    period: 1,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'BacABank',
    value: 4.75,
    threshold: '',
    period: 2,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'BacABank',
    value: 4.75,
    threshold: '',
    period: 3,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'BacABank',
    value: 7.5,
    threshold: '',
    period: 6,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'BacABank',
    value: 7.6,
    threshold: '',
    period: 9,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'BacABank',
    value: 7.8,
    threshold: '',
    period: 12,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'BacABank',
    value: 7.8,
    threshold: '',
    period: 13,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'BacABank',
    value: 7.8,
    threshold: '',
    period: 18,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'BacABank',
    value: 7.8,
    threshold: '',
    period: 24,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'BacABank',
    value: 7.8,
    threshold: '',
    period: 36,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'BaoVietBank',
    value: 0.5,
    threshold: '',
    period: 0,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'BaoVietBank',
    value: 4.75,
    threshold: '',
    period: 1,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'BaoVietBank',
    value: 4.75,
    threshold: '',
    period: 2,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'BaoVietBank',
    value: 4.75,
    threshold: '',
    period: 3,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'BaoVietBank',
    value: 6.85,
    threshold: '',
    period: 6,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'BaoVietBank',
    value: 6.9,
    threshold: '',
    period: 9,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'BaoVietBank',
    value: 7.95,
    threshold: '',
    period: 12,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'BaoVietBank',
    value: 7.99,
    threshold: '',
    period: 13,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'BaoVietBank',
    value: 7.6,
    threshold: '',
    period: 18,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'BaoVietBank',
    value: 7.6,
    threshold: '',
    period: 24,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'BaoVietBank',
    value: 7.6,
    threshold: '',
    period: 36,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'DongABank',
    value: -10,
    threshold: '',
    period: 0,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'DongABank',
    value: 4.75,
    threshold: '',
    period: 1,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'DongABank',
    value: 4.75,
    threshold: '',
    period: 2,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'DongABank',
    value: 4.75,
    threshold: '',
    period: 3,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'DongABank',
    value: 7.0,
    threshold: '',
    period: 6,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'DongABank',
    value: 7.2,
    threshold: '',
    period: 9,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'DongABank',
    value: 7.4,
    threshold: '',
    period: 12,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'DongABank',
    value: 7.6,
    threshold: '',
    period: 13,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'DongABank',
    value: 7.6,
    threshold: '',
    period: 18,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'DongABank',
    value: 7.6,
    threshold: '',
    period: 24,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'DongABank',
    value: 7.6,
    threshold: '',
    period: 36,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'Eximbank',
    value: 0.2,
    threshold: '',
    period: 0,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'Eximbank',
    value: 4.7,
    threshold: '',
    period: 1,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'Eximbank',
    value: 4.7,
    threshold: '',
    period: 2,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'Eximbank',
    value: 4.75,
    threshold: '',
    period: 3,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'Eximbank',
    value: 5.6,
    threshold: '',
    period: 6,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'Eximbank',
    value: 5.8,
    threshold: '',
    period: 9,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'Eximbank',
    value: 7.2,
    threshold: '',
    period: 12,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'Eximbank',
    value: 8.4,
    threshold: '',
    period: 13,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'Eximbank',
    value: 7.4,
    threshold: '',
    period: 18,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'Eximbank',
    value: 8.4,
    threshold: '',
    period: 24,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'Eximbank',
    value: 7.5,
    threshold: '',
    period: 36,
  },
  { lastUpdate: '2020-04-17', online: true, bank: 'HDBank', value: -10, threshold: '', period: 0 },
  { lastUpdate: '2020-04-17', online: true, bank: 'HDBank', value: 4.75, threshold: '', period: 1 },
  { lastUpdate: '2020-04-17', online: true, bank: 'HDBank', value: 4.75, threshold: '', period: 2 },
  { lastUpdate: '2020-04-17', online: true, bank: 'HDBank', value: 4.75, threshold: '', period: 3 },
  { lastUpdate: '2020-04-17', online: true, bank: 'HDBank', value: 6.9, threshold: '', period: 6 },
  { lastUpdate: '2020-04-17', online: true, bank: 'HDBank', value: 6.9, threshold: '', period: 9 },
  { lastUpdate: '2020-04-17', online: true, bank: 'HDBank', value: 7.4, threshold: '', period: 12 },
  { lastUpdate: '2020-04-17', online: true, bank: 'HDBank', value: 7.5, threshold: '', period: 13 },
  { lastUpdate: '2020-04-17', online: true, bank: 'HDBank', value: 7.5, threshold: '', period: 18 },
  { lastUpdate: '2020-04-17', online: true, bank: 'HDBank', value: 7.1, threshold: '', period: 24 },
  { lastUpdate: '2020-04-17', online: true, bank: 'HDBank', value: 7.1, threshold: '', period: 36 },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'KienLongBank',
    value: -10,
    threshold: '',
    period: 0,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'KienLongBank',
    value: 4.55,
    threshold: '',
    period: 1,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'KienLongBank',
    value: 4.65,
    threshold: '',
    period: 2,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'KienLongBank',
    value: 4.75,
    threshold: '',
    period: 3,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'KienLongBank',
    value: 6.8,
    threshold: '',
    period: 6,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'KienLongBank',
    value: 6.8,
    threshold: '',
    period: 9,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'KienLongBank',
    value: 7.5,
    threshold: '',
    period: 12,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'KienLongBank',
    value: 7.7,
    threshold: '',
    period: 13,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'KienLongBank',
    value: 7.9,
    threshold: '',
    period: 18,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'KienLongBank',
    value: 7.9,
    threshold: '',
    period: 24,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'KienLongBank',
    value: 7.7,
    threshold: '',
    period: 36,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'LienVietPostBank',
    value: -10,
    threshold: '',
    period: 0,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'LienVietPostBank',
    value: 4.3,
    threshold: '',
    period: 1,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'LienVietPostBank',
    value: 4.3,
    threshold: '',
    period: 2,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'LienVietPostBank',
    value: 4.75,
    threshold: '',
    period: 3,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'LienVietPostBank',
    value: 5.3,
    threshold: '',
    period: 6,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'LienVietPostBank',
    value: 5.4,
    threshold: '',
    period: 9,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'LienVietPostBank',
    value: 6.8,
    threshold: '',
    period: 12,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'LienVietPostBank',
    value: 6.8,
    threshold: '',
    period: 13,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'LienVietPostBank',
    value: 6.9,
    threshold: '',
    period: 18,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'LienVietPostBank',
    value: 6.9,
    threshold: '',
    period: 24,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'LienVietPostBank',
    value: 6.9,
    threshold: '',
    period: 36,
  },
  { lastUpdate: '2020-04-17', online: true, bank: 'MBB', value: 0.2, threshold: '', period: 0 },
  { lastUpdate: '2020-04-17', online: true, bank: 'MBB', value: 4.4, threshold: '', period: 1 },
  { lastUpdate: '2020-04-17', online: true, bank: 'MBB', value: 4.5, threshold: '', period: 2 },
  { lastUpdate: '2020-04-17', online: true, bank: 'MBB', value: 4.75, threshold: '', period: 3 },
  { lastUpdate: '2020-04-17', online: true, bank: 'MBB', value: 6.0, threshold: '', period: 6 },
  { lastUpdate: '2020-04-17', online: true, bank: 'MBB', value: 6.3, threshold: '', period: 9 },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'MBB',
    value: 7.2,
    threshold: 'Từ 200 tỉ',
    period: 12,
  },
  { lastUpdate: '2020-04-17', online: true, bank: 'MBB', value: 6.4, threshold: '', period: 13 },
  { lastUpdate: '2020-04-17', online: true, bank: 'MBB', value: 6.7, threshold: '', period: 18 },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'MBB',
    value: 7.4,
    threshold: 'Từ 200 tỉ',
    period: 24,
  },
  { lastUpdate: '2020-04-17', online: true, bank: 'MBB', value: 7.1, threshold: '', period: 36 },
  { lastUpdate: '2020-04-17', online: true, bank: 'MSB', value: -10, threshold: '', period: 0 },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'MSB',
    value: 4.75,
    threshold: 'Từ  1 tỉ',
    period: 1,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'MSB',
    value: 4.75,
    threshold: 'Từ 1 tỉ',
    period: 2,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'MSB',
    value: 4.75,
    threshold: 'Từ  1 tỉ',
    period: 3,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'MSB',
    value: 7.1,
    threshold: 'Từ  1 tỉ',
    period: 6,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'MSB',
    value: 7.2,
    threshold: 'Từ  1 tỉ',
    period: 9,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'MSB',
    value: 7.3,
    threshold: 'Từ  1 tỉ',
    period: 12,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'MSB',
    value: 7.4,
    threshold: 'Từ  1 tỉ',
    period: 13,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'MSB',
    value: 7.7,
    threshold: 'Từ  1 tỉ',
    period: 18,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'MSB',
    value: 7.8,
    threshold: 'Từ  1 tỉ',
    period: 24,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'MSB',
    value: 7.8,
    threshold: 'Từ  1 tỉ',
    period: 36,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'Nam A Bank',
    value: 0.5,
    threshold: '',
    period: 0,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'Nam A Bank',
    value: 4.75,
    threshold: '',
    period: 1,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'Nam A Bank',
    value: 4.75,
    threshold: '',
    period: 2,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'Nam A Bank',
    value: 4.75,
    threshold: '',
    period: 3,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'Nam A Bank',
    value: 8.0,
    threshold: '',
    period: 6,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'Nam A Bank',
    value: 8.05,
    threshold: '',
    period: 9,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'Nam A Bank',
    value: 8.3,
    threshold: '',
    period: 12,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'Nam A Bank',
    value: -10,
    threshold: '',
    period: 13,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'Nam A Bank',
    value: 8.4,
    threshold: '',
    period: 18,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'Nam A Bank',
    value: 8.2,
    threshold: '',
    period: 24,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'Nam A Bank',
    value: 8.4,
    threshold: '',
    period: 36,
  },
  { lastUpdate: '2020-04-17', online: true, bank: 'NCB', value: 0.3, threshold: '', period: 0 },
  { lastUpdate: '2020-04-17', online: true, bank: 'NCB', value: 4.5, threshold: '', period: 1 },
  { lastUpdate: '2020-04-17', online: true, bank: 'NCB', value: 4.6, threshold: '', period: 2 },
  { lastUpdate: '2020-04-17', online: true, bank: 'NCB', value: 4.75, threshold: '', period: 3 },
  { lastUpdate: '2020-04-17', online: true, bank: 'NCB', value: 7.5, threshold: '', period: 6 },
  { lastUpdate: '2020-04-17', online: true, bank: 'NCB', value: 7.55, threshold: '', period: 9 },
  { lastUpdate: '2020-04-17', online: true, bank: 'NCB', value: 8.0, threshold: '', period: 12 },
  { lastUpdate: '2020-04-17', online: true, bank: 'NCB', value: 8.1, threshold: '', period: 13 },
  { lastUpdate: '2020-04-17', online: true, bank: 'NCB', value: 8.15, threshold: '', period: 18 },
  { lastUpdate: '2020-04-17', online: true, bank: 'NCB', value: 8.3, threshold: '', period: 24 },
  { lastUpdate: '2020-04-17', online: true, bank: 'NCB', value: 8.3, threshold: '', period: 36 },
  { lastUpdate: '2020-04-17', online: true, bank: 'OCB', value: 0.1, threshold: '', period: 0 },
  { lastUpdate: '2020-04-17', online: true, bank: 'OCB', value: 4.7, threshold: '', period: 1 },
  { lastUpdate: '2020-04-17', online: true, bank: 'OCB', value: 4.7, threshold: '', period: 2 },
  { lastUpdate: '2020-04-17', online: true, bank: 'OCB', value: 4.75, threshold: '', period: 3 },
  { lastUpdate: '2020-04-17', online: true, bank: 'OCB', value: 7.1, threshold: '', period: 6 },
  { lastUpdate: '2020-04-17', online: true, bank: 'OCB', value: 7.2, threshold: '', period: 9 },
  { lastUpdate: '2020-04-17', online: true, bank: 'OCB', value: 7.3, threshold: '', period: 12 },
  { lastUpdate: '2020-04-17', online: true, bank: 'OCB', value: -10, threshold: '', period: 13 },
  { lastUpdate: '2020-04-17', online: true, bank: 'OCB', value: 7.4, threshold: '', period: 18 },
  { lastUpdate: '2020-04-17', online: true, bank: 'OCB', value: 7.6, threshold: '', period: 24 },
  { lastUpdate: '2020-04-17', online: true, bank: 'OCB', value: 7.6, threshold: '', period: 36 },
  { lastUpdate: '2020-04-17', online: true, bank: 'PGBank', value: -10, threshold: '', period: 0 },
  { lastUpdate: '2020-04-17', online: true, bank: 'PGBank', value: 4.75, threshold: '', period: 1 },
  { lastUpdate: '2020-04-17', online: true, bank: 'PGBank', value: 4.75, threshold: '', period: 2 },
  { lastUpdate: '2020-04-17', online: true, bank: 'PGBank', value: 4.75, threshold: '', period: 3 },
  { lastUpdate: '2020-04-17', online: true, bank: 'PGBank', value: 6.7, threshold: '', period: 6 },
  { lastUpdate: '2020-04-17', online: true, bank: 'PGBank', value: 6.7, threshold: '', period: 9 },
  { lastUpdate: '2020-04-17', online: true, bank: 'PGBank', value: 7.3, threshold: '', period: 12 },
  { lastUpdate: '2020-04-17', online: true, bank: 'PGBank', value: 7.3, threshold: '', period: 13 },
  { lastUpdate: '2020-04-17', online: true, bank: 'PGBank', value: 7.6, threshold: '', period: 18 },
  { lastUpdate: '2020-04-17', online: true, bank: 'PGBank', value: 7.6, threshold: '', period: 24 },
  { lastUpdate: '2020-04-17', online: true, bank: 'PGBank', value: 7.6, threshold: '', period: 36 },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'PVcomBank',
    value: -10,
    threshold: '',
    period: 0,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'PVcomBank',
    value: 4.75,
    threshold: '',
    period: 1,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'PVcomBank',
    value: 4.75,
    threshold: '',
    period: 2,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'PVcomBank',
    value: 4.75,
    threshold: '',
    period: 3,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'PVcomBank',
    value: 7.4,
    threshold: '',
    period: 6,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'PVcomBank',
    value: 7.69,
    threshold: '',
    period: 9,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'PVcomBank',
    value: 7.9,
    threshold: '',
    period: 12,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'PVcomBank',
    value: -10,
    threshold: '',
    period: 13,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'PVcomBank',
    value: 7.99,
    threshold: '',
    period: 18,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'PVcomBank',
    value: 7.99,
    threshold: '',
    period: 24,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'PVcomBank',
    value: 7.99,
    threshold: '',
    period: 36,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'Sacombank',
    value: -10,
    threshold: '',
    period: 0,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'Sacombank',
    value: 4.5,
    threshold: '',
    period: 1,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'Sacombank',
    value: 4.6,
    threshold: '',
    period: 2,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'Sacombank',
    value: 4.7,
    threshold: '',
    period: 3,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'Sacombank',
    value: 6.2,
    threshold: 'Dưới 200 triệu',
    period: 6,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'Sacombank',
    value: 6.4,
    threshold: '',
    period: 9,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'Sacombank',
    value: 6.8,
    threshold: 'Dưới 200 triệu',
    period: 12,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'Sacombank',
    value: 7.9,
    threshold: '',
    period: 13,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'Sacombank',
    value: 7.3,
    threshold: 'Dưới 200 triệu',
    period: 18,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'Sacombank',
    value: 7.5,
    threshold: 'Dưới 200 triệu',
    period: 24,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'Sacombank',
    value: 7.6,
    threshold: 'Dưới 200 triệu',
    period: 36,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'Saigonbank',
    value: 0.2,
    threshold: '',
    period: 0,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'Saigonbank',
    value: 4.75,
    threshold: '',
    period: 1,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'Saigonbank',
    value: 4.75,
    threshold: '',
    period: 2,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'Saigonbank',
    value: 4.75,
    threshold: '',
    period: 3,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'Saigonbank',
    value: 6.6,
    threshold: '',
    period: 6,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'Saigonbank',
    value: 6.6,
    threshold: '',
    period: 9,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'Saigonbank',
    value: 7.2,
    threshold: '',
    period: 12,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'Saigonbank',
    value: 7.6,
    threshold: '',
    period: 13,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'Saigonbank',
    value: 7.6,
    threshold: '',
    period: 18,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'Saigonbank',
    value: 7.6,
    threshold: '',
    period: 24,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'Saigonbank',
    value: 7.6,
    threshold: '',
    period: 36,
  },
  { lastUpdate: '2020-04-17', online: true, bank: 'SCB', value: -10, threshold: '', period: 0 },
  { lastUpdate: '2020-04-17', online: true, bank: 'SCB', value: 4.75, threshold: '', period: 1 },
  { lastUpdate: '2020-04-17', online: true, bank: 'SCB', value: 4.75, threshold: '', period: 2 },
  { lastUpdate: '2020-04-17', online: true, bank: 'SCB', value: 4.75, threshold: '', period: 3 },
  { lastUpdate: '2020-04-17', online: true, bank: 'SCB', value: 7.1, threshold: '', period: 6 },
  { lastUpdate: '2020-04-17', online: true, bank: 'SCB', value: 7.1, threshold: '', period: 9 },
  { lastUpdate: '2020-04-17', online: true, bank: 'SCB', value: 7.5, threshold: '', period: 12 },
  { lastUpdate: '2020-04-17', online: true, bank: 'SCB', value: 7.7, threshold: '', period: 13 },
  { lastUpdate: '2020-04-17', online: true, bank: 'SCB', value: 7.7, threshold: '', period: 18 },
  { lastUpdate: '2020-04-17', online: true, bank: 'SCB', value: 7.55, threshold: '', period: 24 },
  { lastUpdate: '2020-04-17', online: true, bank: 'SCB', value: 7.55, threshold: '', period: 36 },
  { lastUpdate: '2020-04-17', online: true, bank: 'SeABank', value: -10, threshold: '', period: 0 },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'SeABank',
    value: 4.75,
    threshold: '',
    period: 1,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'SeABank',
    value: 4.75,
    threshold: '',
    period: 2,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'SeABank',
    value: 4.75,
    threshold: '',
    period: 3,
  },
  { lastUpdate: '2020-04-17', online: true, bank: 'SeABank', value: 5.8, threshold: '', period: 6 },
  { lastUpdate: '2020-04-17', online: true, bank: 'SeABank', value: 6.2, threshold: '', period: 9 },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'SeABank',
    value: 6.8,
    threshold: '',
    period: 12,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'SeABank',
    value: -10,
    threshold: '',
    period: 13,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'SeABank',
    value: 6.85,
    threshold: '',
    period: 18,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'SeABank',
    value: 6.9,
    threshold: '',
    period: 24,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'SeABank',
    value: 6.95,
    threshold: '',
    period: 36,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'SHB',
    value: 0.2,
    threshold: 'Từ 2 tỉ',
    period: 0,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'SHB',
    value: 4.35,
    threshold: 'Từ 2 tỉ',
    period: 1,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'SHB',
    value: 4.45,
    threshold: 'Từ 2 tỉ',
    period: 2,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'SHB',
    value: 4.55,
    threshold: 'Từ 2 tỉ',
    period: 3,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'SHB',
    value: 6.6,
    threshold: 'Từ 2 tỉ',
    period: 6,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'SHB',
    value: 6.7,
    threshold: 'Từ 2 tỉ',
    period: 9,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'SHB',
    value: 6.8,
    threshold: 'Từ 2 tỉ',
    period: 12,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'SHB',
    value: 6.8,
    threshold: 'Từ 2 tỉ',
    period: 13,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'SHB',
    value: 7.1,
    threshold: 'Từ 2 tỉ',
    period: 18,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'SHB',
    value: 7.1,
    threshold: 'Từ 2 tỉ',
    period: 24,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'SHB',
    value: 7.2,
    threshold: 'Từ 2 tỉ',
    period: 36,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'Techcombank',
    value: 0.1,
    threshold: '',
    period: 0,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'Techcombank',
    value: 4.65,
    threshold: 'Từ 3 tỉ và KH trên 50 tuổi',
    period: 1,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'Techcombank',
    value: 4.65,
    threshold: 'Từ 3 tỉ và KH trên 50 tuổi',
    period: 2,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'Techcombank',
    value: 4.65,
    threshold: 'Từ 3 tỉ và KH trên 50 tuổi',
    period: 3,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'Techcombank',
    value: 6.6,
    threshold: 'Từ 3 tỉ và KH trên 50 tuổi',
    period: 6,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'Techcombank',
    value: 6.1,
    threshold: 'Từ 3 tỉ và KH trên 50 tuổi',
    period: 9,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'Techcombank',
    value: 6.7,
    threshold: 'Từ 3 tỉ và KH trên 50 tuổi',
    period: 12,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'Techcombank',
    value: 6.4,
    threshold: 'Từ 3 tỉ và KH trên 50 tuổi',
    period: 13,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'Techcombank',
    value: 6.7,
    threshold: 'Từ 3 tỉ và KH trên 50 tuổi',
    period: 18,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'Techcombank',
    value: 6.5,
    threshold: 'Từ 3 tỉ và KH trên 50 tuổi',
    period: 24,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'Techcombank',
    value: 6.5,
    threshold: 'Từ 3 tỉ và KH trên 50 tuổi',
    period: 36,
  },
  { lastUpdate: '2020-04-17', online: true, bank: 'TPBank', value: 0.3, threshold: '', period: 0 },
  { lastUpdate: '2020-04-17', online: true, bank: 'TPBank', value: 4.75, threshold: '', period: 1 },
  { lastUpdate: '2020-04-17', online: true, bank: 'TPBank', value: 4.75, threshold: '', period: 2 },
  { lastUpdate: '2020-04-17', online: true, bank: 'TPBank', value: 4.75, threshold: '', period: 3 },
  { lastUpdate: '2020-04-17', online: true, bank: 'TPBank', value: 6.8, threshold: '', period: 6 },
  { lastUpdate: '2020-04-17', online: true, bank: 'TPBank', value: 7.05, threshold: '', period: 9 },
  { lastUpdate: '2020-04-17', online: true, bank: 'TPBank', value: 7.4, threshold: '', period: 12 },
  { lastUpdate: '2020-04-17', online: true, bank: 'TPBank', value: -10, threshold: '', period: 13 },
  { lastUpdate: '2020-04-17', online: true, bank: 'TPBank', value: 7.6, threshold: '', period: 18 },
  { lastUpdate: '2020-04-17', online: true, bank: 'TPBank', value: 7.6, threshold: '', period: 24 },
  { lastUpdate: '2020-04-17', online: true, bank: 'TPBank', value: 7.6, threshold: '', period: 36 },
  { lastUpdate: '2020-04-17', online: true, bank: 'VIB', value: 0.5, threshold: '', period: 0 },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'VIB',
    value: 4.75,
    threshold: 'Từ 5 tỉ',
    period: 1,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'VIB',
    value: 4.75,
    threshold: 'Từ 5 tỉ',
    period: 2,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'VIB',
    value: 4.75,
    threshold: 'Từ 5 tỉ',
    period: 3,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'VIB',
    value: 7.0,
    threshold: 'Từ 5 tỉ',
    period: 6,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'VIB',
    value: 7.0,
    threshold: 'Từ 5 tỉ',
    period: 9,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'VIB',
    value: 7.59,
    threshold: 'Từ 5 tỉ',
    period: 12,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'VIB',
    value: 7.59,
    threshold: 'Từ 5 tỉ',
    period: 13,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'VIB',
    value: 7.6,
    threshold: 'Từ 5 tỉ',
    period: 18,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'VIB',
    value: 7.6,
    threshold: 'Từ 5 tỉ',
    period: 24,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'VIB',
    value: 7.6,
    threshold: 'Từ 5 tỉ',
    period: 36,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'VietABank',
    value: -10,
    threshold: '',
    period: 0,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'VietABank',
    value: 4.65,
    threshold: '',
    period: 1,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'VietABank',
    value: 4.65,
    threshold: '',
    period: 2,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'VietABank',
    value: 4.65,
    threshold: '',
    period: 3,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'VietABank',
    value: 7.0,
    threshold: '',
    period: 6,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'VietABank',
    value: 7.1,
    threshold: '',
    period: 9,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'VietABank',
    value: 7.6,
    threshold: '',
    period: 12,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'VietABank',
    value: 7.7,
    threshold: '',
    period: 13,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'VietABank',
    value: 7.7,
    threshold: '',
    period: 18,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'VietABank',
    value: 7.9,
    threshold: '',
    period: 24,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'VietABank',
    value: 7.7,
    threshold: '',
    period: 36,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'VietBank',
    value: -10,
    threshold: '',
    period: 0,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'VietBank',
    value: 4.75,
    threshold: '',
    period: 1,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'VietBank',
    value: 4.75,
    threshold: '',
    period: 2,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'VietBank',
    value: 4.75,
    threshold: '',
    period: 3,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'VietBank',
    value: 7.4,
    threshold: '',
    period: 6,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'VietBank',
    value: 7.7,
    threshold: '',
    period: 9,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'VietBank',
    value: 7.8,
    threshold: '',
    period: 12,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'VietBank',
    value: 7.9,
    threshold: '',
    period: 13,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'VietBank',
    value: 7.9,
    threshold: '',
    period: 18,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'VietBank',
    value: 7.9,
    threshold: '',
    period: 24,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'VietBank',
    value: 7.9,
    threshold: '',
    period: 36,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'VietCapitalBank',
    value: -10,
    threshold: '',
    period: 0,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'VietCapitalBank',
    value: 4.7,
    threshold: '',
    period: 1,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'VietCapitalBank',
    value: 4.7,
    threshold: '',
    period: 2,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'VietCapitalBank',
    value: 4.7,
    threshold: '',
    period: 3,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'VietCapitalBank',
    value: 7.0,
    threshold: '',
    period: 6,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'VietCapitalBank',
    value: 7.1,
    threshold: '',
    period: 9,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'VietCapitalBank',
    value: 7.5,
    threshold: '',
    period: 12,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'VietCapitalBank',
    value: 8.5,
    threshold: '',
    period: 13,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'VietCapitalBank',
    value: 7.5,
    threshold: '',
    period: 18,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'VietCapitalBank',
    value: 7.5,
    threshold: '',
    period: 24,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'VietCapitalBank',
    value: 7.5,
    threshold: '',
    period: 36,
  },
  { lastUpdate: '2020-04-17', online: true, bank: 'VPBank', value: -10, threshold: '', period: 0 },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'VPBank',
    value: 4.65,
    threshold: 'Từ 10 tỉ',
    period: 1,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'VPBank',
    value: 4.65,
    threshold: 'Từ 10 tỉ',
    period: 2,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'VPBank',
    value: 4.75,
    threshold: 'Từ 10 tỉ',
    period: 3,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'VPBank',
    value: 7.0,
    threshold: 'Từ 10 tỉ',
    period: 6,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'VPBank',
    value: 7.0,
    threshold: 'Từ 10 tỉ',
    period: 9,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'VPBank',
    value: 7.1,
    threshold: 'Từ 10 tỉ',
    period: 12,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'VPBank',
    value: 7.1,
    threshold: 'Từ 10 tỉ',
    period: 13,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'VPBank',
    value: 7.2,
    threshold: 'Từ 10 tỉ',
    period: 18,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'VPBank',
    value: 7.2,
    threshold: 'Từ 10 tỉ',
    period: 24,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'VPBank',
    value: 7.2,
    threshold: 'Từ 10 tỉ',
    period: 36,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'ANZ Bank',
    value: 0.0,
    threshold: '',
    period: 0,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'ANZ Bank',
    value: 1.5,
    threshold: '',
    period: 1,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'ANZ Bank',
    value: 1.5,
    threshold: '',
    period: 2,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'ANZ Bank',
    value: 1.5,
    threshold: '',
    period: 3,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'ANZ Bank',
    value: 1.5,
    threshold: '',
    period: 6,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'ANZ Bank',
    value: -100,
    threshold: '',
    period: 9,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'ANZ Bank',
    value: -100,
    threshold: '',
    period: 12,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'ANZ Bank',
    value: -100,
    threshold: '',
    period: 13,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'ANZ Bank',
    value: -100,
    threshold: '',
    period: 18,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'ANZ Bank',
    value: -100,
    threshold: '',
    period: 24,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'ANZ Bank',
    value: -100,
    threshold: '',
    period: 36,
  },
  { lastUpdate: '2020-04-17', online: true, bank: 'HSBC', value: -10, threshold: '', period: 0 },
  { lastUpdate: '2020-04-17', online: true, bank: 'HSBC', value: 0.5, threshold: '', period: 1 },
  { lastUpdate: '2020-04-17', online: true, bank: 'HSBC', value: 0.5, threshold: '', period: 2 },
  { lastUpdate: '2020-04-17', online: true, bank: 'HSBC', value: 1.25, threshold: '', period: 3 },
  { lastUpdate: '2020-04-17', online: true, bank: 'HSBC', value: 1.75, threshold: '', period: 6 },
  { lastUpdate: '2020-04-17', online: true, bank: 'HSBC', value: 1.75, threshold: '', period: 9 },
  { lastUpdate: '2020-04-17', online: true, bank: 'HSBC', value: 2.75, threshold: '', period: 12 },
  { lastUpdate: '2020-04-17', online: true, bank: 'HSBC', value: -10, threshold: '', period: 13 },
  { lastUpdate: '2020-04-17', online: true, bank: 'HSBC', value: 2.75, threshold: '', period: 18 },
  { lastUpdate: '2020-04-17', online: true, bank: 'HSBC', value: 2.75, threshold: '', period: 24 },
  { lastUpdate: '2020-04-17', online: true, bank: 'HSBC', value: 2.75, threshold: '', period: 36 },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'Standard Chartered',
    value: -10,
    threshold: '',
    period: 0,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'Standard Chartered',
    value: 1.32,
    threshold: '',
    period: 1,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'Standard Chartered',
    value: 1.58,
    threshold: '',
    period: 2,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'Standard Chartered',
    value: 1.87,
    threshold: '',
    period: 3,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'Standard Chartered',
    value: 1.87,
    threshold: '',
    period: 6,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'Standard Chartered',
    value: 1.87,
    threshold: '',
    period: 9,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'Standard Chartered',
    value: 1.87,
    threshold: '',
    period: 12,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'Standard Chartered',
    value: 1.87,
    threshold: '',
    period: 13,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'Standard Chartered',
    value: 1.87,
    threshold: '',
    period: 18,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'Standard Chartered',
    value: 1.87,
    threshold: '',
    period: 24,
  },
  {
    lastUpdate: '2020-04-17',
    online: true,
    bank: 'Standard Chartered',
    value: 1.87,
    threshold: '',
    period: 36,
  },
  { lastUpdate: '2020-04-17', online: true, bank: 'IVB', value: -10, threshold: '', period: 0 },
  { lastUpdate: '2020-04-17', online: true, bank: 'IVB', value: 4.75, threshold: '', period: 1 },
  { lastUpdate: '2020-04-17', online: true, bank: 'IVB', value: 4.75, threshold: '', period: 2 },
  { lastUpdate: '2020-04-17', online: true, bank: 'IVB', value: 4.75, threshold: '', period: 3 },
  { lastUpdate: '2020-04-17', online: true, bank: 'IVB', value: 6.8, threshold: '', period: 6 },
  { lastUpdate: '2020-04-17', online: true, bank: 'IVB', value: 6.9, threshold: '', period: 9 },
  { lastUpdate: '2020-04-17', online: true, bank: 'IVB', value: 7.6, threshold: '', period: 12 },
  { lastUpdate: '2020-04-17', online: true, bank: 'IVB', value: 7.7, threshold: '', period: 13 },
  { lastUpdate: '2020-04-17', online: true, bank: 'IVB', value: 7.8, threshold: '', period: 18 },
  { lastUpdate: '2020-04-17', online: true, bank: 'IVB', value: 7.9, threshold: '', period: 24 },
  { lastUpdate: '2020-04-17', online: true, bank: 'IVB', value: 7.9, threshold: '', period: 36 },
]
